# Generated by Django 5.2.7 on 2026-01-22 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertiesDetails",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("pg_name", models.CharField(max_length=100)),
                ("total_rooms", models.IntegerField()),
                ("address", models.TextField(blank=True, null=True)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("pg_photo", models.CharField(blank=True, max_length=100, null=True)),
                ("video_tour", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("amenities", models.TextField(blank=True, null=True)),
                (
                    "maximum_charges",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "minium_charges",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Complaint",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("subject", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("status", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.propertiesdetails",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RatingReview",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("rating", models.PositiveIntegerField()),
                ("review", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                (
                    "pg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.propertiesdetails",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("tenant", "pg")},
            },
        ),
        migrations.CreateModel(
            name="RoomDetails",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("room_number", models.CharField(max_length=30)),
                ("floor", models.IntegerField()),
                ("room_type", models.CharField(max_length=50)),
                ("capacity", models.PositiveIntegerField()),
                ("current_occupancy", models.PositiveIntegerField()),
                (
                    "monthly_rent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "daily_rent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("status", models.CharField(max_length=20)),
                ("amenities", models.TextField(blank=True, null=True)),
                ("room_photo", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "room_videos",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("is_available", models.IntegerField()),
                (
                    "pg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.propertiesdetails",
                    ),
                ),
            ],
            options={
                "unique_together": {("pg", "room_number")},
            },
        ),
    ]
