# Generated by Django 5.2.7 on 2025-11-06 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='tenants.tenantdetail'),
        ),
        migrations.AddField(
            model_name='propertiesdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='pg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='properties.propertiesdetails'),
        ),
        migrations.AddField(
            model_name='ratingreview',
            name='pg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_reviews', to='properties.propertiesdetails'),
        ),
        migrations.AddField(
            model_name='ratingreview',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_reviews', to='tenants.tenantdetail'),
        ),
        migrations.AddField(
            model_name='roomdetails',
            name='pg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='properties.propertiesdetails'),
        ),
        migrations.AlterUniqueTogether(
            name='ratingreview',
            unique_together={('tenant', 'pg')},
        ),
        migrations.AlterUniqueTogether(
            name='roomdetails',
            unique_together={('pg', 'room_number')},
        ),
    ]
