# Generated by Django 5.2.7 on 2026-02-01 07:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="propertiesdetails",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="propertiesdetails",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="propertiesdetails",
            name="pincode",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="propertiesdetails",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name="propertiesdetails",
            index=models.Index(
                fields=["latitude", "longitude"], name="properties__latitud_7829ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propertiesdetails",
            index=models.Index(
                fields=["country"], name="properties__country_ec224d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propertiesdetails",
            index=models.Index(fields=["state"], name="properties__state_d1cd42_idx"),
        ),
        migrations.AddIndex(
            model_name="propertiesdetails",
            index=models.Index(fields=["city"], name="properties__city_71ed96_idx"),
        ),
        migrations.AddIndex(
            model_name="propertiesdetails",
            index=models.Index(
                fields=["pincode"], name="properties__pincode_10653a_idx"
            ),
        ),
    ]
