# Generated by Django 5.2.7 on 2025-11-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertiesdetails',
            name='amenities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertiesdetails',
            name='maximum_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='propertiesdetails',
            name='minium_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=50),
        ),
        migrations.AlterField(
            model_name='propertiesdetails',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
