# Generated by Django 5.2.7 on 2026-02-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "properties",
            "0002_propertiesdetails_city_propertiesdetails_country_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ratingreview",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
