# Generated by Django 5.2.7 on 2026-01-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_alter_complaint_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomdetails",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
