# Generated by Django 5.2.7 on 2026-01-22 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantCharge",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("charge_type", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_recurring", models.IntegerField()),
                ("created_at", models.DateTimeField()),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TenantDetail",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "homecontact",
                    models.CharField(db_column="homeContact", max_length=15),
                ),
                ("permanentaddress", models.TextField(db_column="permanentAddress")),
                ("idname", models.CharField(db_column="IdName", max_length=100)),
                (
                    "uniqueidnumber",
                    models.CharField(
                        db_column="uniqueIDNumber", max_length=100, unique=True
                    ),
                ),
                (
                    "tenantphoto",
                    models.CharField(
                        blank=True, db_column="tenantPhoto", max_length=100, null=True
                    ),
                ),
                (
                    "addressproof",
                    models.CharField(
                        blank=True, db_column="addressProof", max_length=100, null=True
                    ),
                ),
                ("rent_type", models.CharField(max_length=10)),
                ("status", models.CharField(max_length=50)),
                ("joined_date", models.DateField()),
                ("vacated_date", models.DateField(blank=True, null=True)),
                (
                    "pg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.propertiesdetails",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.roomdetails",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TenantOldDetail",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("joined_date", models.DateField()),
                ("vacated_date", models.DateField()),
                (
                    "pg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="properties.propertiesdetails",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="properties.roomdetails",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TenantPaymentDetail",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_date", models.DateTimeField()),
                ("payment_method", models.CharField(max_length=50)),
                ("transaction_id", models.CharField(max_length=100, unique=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "pg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.propertiesdetails",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.roomdetails",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
