# Generated by Django 5.2.7 on 2025-11-06 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeContact', models.CharField(max_length=15)),
                ('permanentAddress', models.TextField()),
                ('IdName', models.CharField(default='Aadhar Card', max_length=100)),
                ('uniqueIDNumber', models.CharField(max_length=100, unique=True)),
                ('tenantPhoto', models.FileField(blank=True, null=True, upload_to='tenant_photos/')),
                ('addressProof', models.FileField(blank=True, null=True, upload_to='address_proofs/')),
                ('rent_type', models.CharField(choices=[('monthly', 'Monthly'), ('daily', 'Daily')], default='monthly', max_length=10)),
                ('status', models.CharField(default='active', max_length=50)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('vacated_date', models.DateField(blank=True, null=True)),
                ('pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants_pg', to='properties.propertiesdetails')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants_room', to='properties.roomdetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_detail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TenantCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('rent', 'Base Rent'), ('service', 'Service Charge'), ('maintenance', 'Maintenance Fee'), ('discount', 'Discount'), ('penalty', 'Penalty'), ('deposit', 'Security Deposit')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_recurring', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='tenants.tenantdetail')),
            ],
        ),
        migrations.CreateModel(
            name='TenantOldDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateField()),
                ('vacated_date', models.DateField()),
                ('pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertiesdetails')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.roomdetails')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenantdetail')),
            ],
        ),
        migrations.CreateModel(
            name='TenantPaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('online', 'Online Payment'), ('other', 'Other')], max_length=50)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants_old_pg', to='properties.propertiesdetails')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants_old_room', to='properties.roomdetails')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenants.tenantdetail')),
            ],
        ),
    ]
