# Generated by Django 5.2.7 on 2025-11-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantdetail',
            name='IdName',
            field=models.CharField(choices=[('Aadhar Card', 'Aadhar Card'), ('PAN Card', 'PAN Card'), ('Driving License', 'Driving License'), ('Passport', 'Passport'), ('Voter ID', 'Voter ID')], default='Aadhar Card', max_length=100),
        ),
    ]
