# Generated by Django 5.2.7 on 2026-01-22 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnerDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_properties", models.IntegerField()),
                (
                    "photo",
                    models.FileField(blank=True, null=True, upload_to="owner_photos/"),
                ),
                (
                    "proof_id_name",
                    models.CharField(
                        choices=[
                            ("Aadhar Card", "Aadhar Card"),
                            ("PAN Card", "PAN Card"),
                            ("Driving License", "Driving License"),
                            ("Passport", "Passport"),
                        ],
                        default="Aadhar Card",
                        max_length=50,
                    ),
                ),
                (
                    "photo_id_proof",
                    models.FileField(
                        blank=True, null=True, upload_to="owner_id_proofs/"
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
